In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../clean_data/cleaned_data.csv')
df.sample(5)

,product_name,brand,category,price,size,love_count,rating,reviews_count,category_1,category_2,category_3,size_oz,size_mL,size_g
2148,VOLUME Shampoo,OUAI,Hair/Shampoo & Conditioner/Shampoo,14.0,10 oz/ 295 mL,6612,2.9704,135,Hair,Shampoo & Conditioner,Shampoo,10.00,295.0,NaN
168,Diamond Lights Finisher,Artist Couture,Makeup/Eye/Eyeshadow,25.0,0.12 oz/ 3.5 g,16048,4.6000,65,Makeup,Eye,Eyeshadow,0.12,NaN,3.5
76,Color Control Cushion Compact Broad Spectrum S...,AMOREPACIFIC,Makeup/Face/BB & CC Cream,60.0,1.05 oz,29848,4.0468,1068,Makeup,Face,BB & CC Cream,1.05,NaN,NaN
1876,Miu Miu Twist Eau de Parfum,Miu Miu,Fragrance/Women/Perfume,73.0,1.7oz/50mL,3101,3.9697,66,Fragrance,Women,Perfume,NaN,NaN,NaN
1954,InvisiScar Resurfacing Treatment,Murad,Skincare/Treatments/Face Serums,35.0,0.5 oz/ 15 mL,10421,4.4046,304,Skincare,Treatments,Face Serums,0.50,15.0,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3082 entries, 0 to 3081
Data columns (total 14 columns):
product_name     3082 non-null object
brand            3082 non-null object
category         3082 non-null object
price            3082 non-null float64
size             3082 non-null object
love_count       3082 non-null int64
rating           3082 non-null float64
reviews_count    3082 non-null int64
category_1       3082 non-null object
category_2       3079 non-null object
category_3       2705 non-null object
size_oz          2086 non-null float64
size_mL          1556 non-null float64
size_g           336 non-null float64
dtypes: float64(5), int64(2), object(7)
memory usage: 337.2+ KB

# Top 10 most expensive products

In [4]:
df.sort_values('price', ascending=False).head(10)

,product_name,brand,category,price,size,love_count,rating,reviews_count,category_1,category_2,category_3,size_oz,size_mL,size_g
852,Airwrap™ Styler,dyson,Hair/Hair Tools/Hair Straighteners & Flat Irons,549.0,Complete styler – for multiple hair types and ...,41668,4.0519,424,Hair,Hair Tools,Hair Straighteners & Flat Irons,NaN,NaN,NaN
771,Advent Calendar,Dr. Barbara Sturm,Skincare/Value & Gift Sets,495.0,na,633,3.8000,5,Skincare,Value & Gift Sets,NaN,NaN,NaN,NaN
855,Supersonic Hair Dryer 23.75 Karat Gold,dyson,Hair/Hair Tools/Hair Dryers,449.0,na,4066,4.7333,15,Hair,Hair Tools,Hair Dryers,NaN,NaN,NaN
796,SpectraLite™ Faceware Pro,Dr. Dennis Gross Skincare,Skincare/High Tech Tools/Anti-Aging,435.0,na,10427,4.6071,28,Skincare,High Tech Tools,Anti-Aging,NaN,NaN,NaN
2050,Trinity Facial Toning Device + Wrinkle Reducer...,NuFACE,Skincare/High Tech Tools/Facial Cleansing Brushes,429.0,na,2050,2.5000,6,Skincare,High Tech Tools,Facial Cleansing Brushes,NaN,NaN,NaN
2046,Trinity + Eye and Lip Enhancer Attachment Bundle,NuFACE,Skincare/High Tech Tools/Facial Cleansing Brushes,429.0,na,8230,3.5758,33,Skincare,High Tech Tools,Facial Cleansing Brushes,NaN,NaN,NaN
853,Supersonic™ Hair Dryer Gift Edition with Red Case,dyson,Hair/Value & Gift Sets,399.0,na,7484,4.1429,14,Hair,Value & Gift Sets,NaN,NaN,NaN,NaN
2049,NuBODY Skin Toning Device,NuFACE,Skincare/High Tech Tools/Anti-Aging,399.0,na,3121,4.3889,18,Skincare,High Tech Tools,Anti-Aging,NaN,NaN,NaN
854,Supersonic Hair Dryer,dyson,Hair/Hair Tools/Hair Dryers,399.0,Iron/ Fuchsia,46901,4.1658,730,Hair,Hair Tools,Hair Dryers,NaN,NaN,NaN
152,Elite Mirror Ten Brush Set,Artis,Makeup/Brushes & Applicators/Brush Sets,370.0,na,5826,4.0833,12,Makeup,Brushes & Applicators,Brush Sets,NaN,NaN,NaN

# Top 10 most popular products

In [5]:
df.sort_values('love_count', ascending=False).head(10)

,product_name,brand,category,price,size,love_count,rating,reviews_count,category_1,category_2,category_3,size_oz,size_mL,size_g
1417,Everlasting Liquid Lipstick,Kat Von D,Makeup/Lip/Lipstick,8.0,0.22 oz/ 6.6 mL,1229798,4.2867,14770,Makeup,Lip,Lipstick,0.220,6.6,NaN
1983,Radiant Creamy Concealer,NARS,Makeup/Face/Concealer,30.0,0.22 oz/ 6 mL,747284,4.3142,11337,Makeup,Face,Concealer,0.220,6.0,NaN
88,Brow Wiz,Anastasia Beverly Hills,Makeup/Eye/Eyebrow,23.0,0.003 oz/ 0.085 g,638003,4.4222,14535,Makeup,Eye,Eyebrow,0.003,NaN,0.085
1667,Translucent Loose Setting Powder,Laura Mercier,Makeup/Face/Setting Spray & Powder,23.0,1 oz/ 30 mL,637818,4.5225,8408,Makeup,Face,Setting Spray & Powder,1.000,30.0,NaN
1985,Blush,NARS,Makeup/Cheek/Blush,30.0,0.16 oz/ 4.8 g,620340,4.6719,17556,Makeup,Cheek,Blush,0.160,NaN,4.800
1201,Obsessions Eyeshadow Palette,HUDA BEAUTY,Makeup/Eye/Eye Palettes,27.0,9 x 0.05 oz/ 1.3 g,609240,4.3113,4645,Makeup,Eye,Eye Palettes,NaN,NaN,NaN
2498,Cream Lip Stain Liquid Lipstick,SEPHORA COLLECTION,Makeup/Lip/Lip Stain,14.0,0.169 oz/ 5 mL,597534,4.3545,9579,Makeup,Lip,Lip Stain,0.169,5.0,NaN
975,Pro Filt'r Soft Matte Longwear Foundation,FENTY BEAUTY by Rihanna,Makeup/Face/Foundation,35.0,1.08 oz/ 32 mL,597158,4.0701,14845,Makeup,Face,Foundation,1.080,32.0,NaN
90,Liquid Lipstick,Anastasia Beverly Hills,Makeup/Lip/Lipstick,20.0,0.11 oz / 3.2 g,545325,3.8439,3978,Makeup,Lip,Lipstick,0.110,NaN,3.200
2880,All Nighter Long-Lasting Makeup Setting Spray,Urban Decay,Makeup/Face/Setting Spray & Powder,15.0,Standard Size - 4 oz/ 118 mL,493821,4.4159,9599,Makeup,Face,Setting Spray & Powder,4.000,118.0,NaN

# Factors on Price

## Brand effect on price

### Top 10 most expensive brand (by mean price)

In [6]:
df.groupby('brand').mean().sort_values('price',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
brand,,,,,,,
dyson,449.000000,25029.750000,4.273475,295.750000,NaN,NaN,NaN
Dr. Barbara Sturm,227.083333,1247.416667,3.868517,12.583333,1.672500,50.000000,NaN
ReFa,223.333333,1562.000000,4.761900,5.666667,NaN,NaN,NaN
LightStim,209.000000,4155.000000,4.446150,9.000000,NaN,NaN,NaN
NuFACE,208.272727,5163.272727,3.906136,56.272727,6.000000,178.000000,NaN
Beachwaver,199.000000,2555.000000,3.928600,14.000000,NaN,NaN,NaN
Kilian,195.833333,3012.000000,4.452358,36.166667,1.945833,57.291667,NaN
Jillian Dempsey,195.000000,2418.000000,4.500000,6.000000,NaN,NaN,NaN
ghd,187.000000,5466.750000,4.186225,119.750000,NaN,NaN,NaN
Bio Ionic,168.500000,3442.166667,4.314417,43.083333,NaN,NaN,NaN

### Top 10 most expensive brand (by median price)

In [7]:
df.groupby('brand').median().sort_values('price',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
brand,,,,,,,
dyson,424.0,24576.0,4.15435,219.5,NaN,NaN,NaN
Kilian,295.0,2687.5,4.36530,20.5,1.7,50.0,NaN
ReFa,220.0,1647.0,5.00000,6.0,NaN,NaN,NaN
Dr. Barbara Sturm,215.0,1212.5,3.81665,5.0,1.0,30.0,NaN
LightStim,209.0,4155.0,4.44615,9.0,NaN,NaN,NaN
ghd,199.0,4804.5,4.24410,47.5,NaN,NaN,NaN
Beachwaver,199.0,2555.0,3.92860,14.0,NaN,NaN,NaN
Jillian Dempsey,195.0,2418.0,4.50000,6.0,NaN,NaN,NaN
Eight & Bob,175.0,166.0,2.00000,1.0,3.4,100.0,NaN
FOREO,169.0,7625.0,4.31340,99.5,NaN,NaN,NaN

## Category effect on Price

### Mean price by main category

In [8]:
df.groupby('category_1').mean().sort_values('price',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
category_1,,,,,,,
Fragrance,62.043301,6772.892157,4.221923,163.666667,2.592230,69.098313,209.772727
Skincare,58.453776,20285.996205,4.210010,404.941176,2.414580,70.127694,86.096094
Tools & Brushes,55.847826,9506.217391,4.090048,212.739130,NaN,NaN,NaN
Hair,48.935399,9371.207289,4.026186,178.252847,6.555806,211.756000,126.790909
Men,37.240741,2323.981481,4.381322,66.314815,4.315417,133.233333,NaN
Bath & Body,36.356250,14747.512500,4.190184,330.337500,5.587286,183.357143,150.777778
Makeup,35.124581,55572.672258,4.107733,1072.985806,0.640547,32.415000,7.001704
Gifts,27.000000,1060.000000,4.800000,5.000000,NaN,NaN,NaN
Mini Size,19.511364,30860.931818,4.194286,989.500000,1.129857,40.801250,6.950000

### check std

In [9]:
df.groupby('category_1').std().sort_values('price',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
category_1,,,,,,,
Hair,64.201944,16300.177593,0.859162,363.509652,3.869092,118.925276,79.657301
Tools & Brushes,57.562108,13256.582461,0.626810,378.415863,NaN,NaN,NaN
Skincare,54.840834,33342.756618,0.724728,877.981901,2.570194,72.943135,102.762075
Fragrance,44.708496,12899.823708,1.004176,460.278653,2.563969,50.236055,210.691642
Makeup,25.498486,107011.677124,0.701552,2476.555102,1.724163,77.977538,12.433133
Men,23.248603,3421.424571,1.112959,125.096012,4.914385,179.457935,NaN
Bath & Body,22.052612,24449.560095,0.501587,666.858950,3.500516,113.183106,79.179823
Mini Size,7.948591,43171.524103,0.401066,2094.119535,0.882580,29.828091,6.069322
Gifts,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### by sub category

In [10]:
df.groupby('category_3').mean().sort_values('price',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
category_3,,,,,,,
Hair Dryers,225.070000,8834.714286,4.163079,140.214286,NaN,NaN,NaN
Hair Straighteners & Flat Irons,181.777222,9948.222222,4.059772,160.000000,NaN,NaN,NaN
Curling Irons,163.292353,6400.117647,3.917118,42.294118,NaN,NaN,NaN
Facial Cleansing Brushes,143.793103,11993.344828,4.237314,148.448276,NaN,NaN,NaN
Anti-Aging,143.354839,5496.483871,3.981026,35.129032,10.000000,296.000000,NaN
Brush Sets,131.444444,31554.222222,4.259489,105.000000,NaN,NaN,NaN
Cleansing Brushes,99.000000,869.000000,5.000000,1.000000,NaN,NaN,NaN
Cologne Gift Sets,84.333333,1195.666667,1.583333,2.666667,NaN,NaN,NaN
Decollete & Neck Creams,83.000000,3991.333333,3.700567,101.000000,1.680000,49.750000,50.0
Face Serums,77.902353,24440.367647,4.247688,401.661765,1.178992,35.405833,NaN

# Brand effect on love counts

### Top 10 most popular brand (by mean)

In [11]:
df.groupby('brand').mean().sort_values('love_count',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
brand,,,,,,,
Kat Von D,24.333333,216541.083333,4.385642,5066.500000,0.619857,23.430000,5.700
NARS,37.166667,212468.916667,4.248050,3964.500000,0.549556,17.875000,4.650
Anastasia Beverly Hills,31.750000,206597.166667,4.336467,3446.000000,0.140000,NaN,3.317
Urban Decay,33.416667,184834.250000,3.695642,5547.000000,2.808000,88.800000,1.200
FENTY BEAUTY by Rihanna,35.000000,181270.416667,3.971717,2986.166667,0.973333,33.400000,7.100
HUDA BEAUTY,43.000000,166299.666667,4.208542,1395.500000,0.746667,20.000000,5.200
Too Faced,23.083333,140292.750000,3.866167,3402.166667,0.438750,8.276667,21.500
Benefit Cosmetics,26.083333,125674.000000,4.353542,3836.250000,0.255250,NaN,7.240
SEPHORA COLLECTION,33.636364,119593.636364,4.014664,1433.454545,0.169000,5.000000,NaN
Hourglass,35.916667,118761.416667,4.327800,2338.583333,0.478750,30.000000,7.025

# Brand effect on ratings

### Top 10 most popular brand (by mean)

In [12]:
by_brand = df.groupby('brand').mean()
by_brand.loc[by_brand.reviews_count >=30].sort_values('rating',ascending= False).head(10)

,price,love_count,rating,reviews_count,size_oz,size_mL,size_g
brand,,,,,,,
Aether Beauty,58.000000,3776.000000,4.903800,56.000000,NaN,NaN,NaN
Montblanc,59.714286,1364.000000,4.895300,30.714286,2.914286,87.857143,NaN
The Art of Shaving,39.166667,841.666667,4.774975,31.333333,3.420000,120.000000,NaN
Ralph Lauren,61.916667,4664.916667,4.729200,283.416667,3.030000,91.555556,NaN
BURBERRY,56.000000,6588.750000,4.705358,147.166667,1.750000,58.888889,NaN
Alpha-H,61.250000,1289.416667,4.661725,57.500000,2.576667,76.250000,NaN
The 7 Virtues,29.000000,2853.166667,4.653692,55.083333,1.201818,35.818182,NaN
Makeup Eraser,20.000000,40140.000000,4.646600,1029.500000,NaN,NaN,NaN
Versace,52.916667,14393.916667,4.640975,271.916667,4.211111,125.555556,NaN
Prada,59.750000,7686.833333,4.635875,167.916667,2.955000,87.625000,NaN